[app]
name="payment-iran"
env="development"

[server]
host="localhost"
port=9091

[novinopay]
merchant_id="test"
callback_url="/novinopay/callback"
init_transaction_url="https://api.novinopay.com/payment/ipg/v2/request"
verify_transaction_url="https://api.novinopay.com/payment/ipg/v2/verification"
