// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/greeting": {
            "get": {
                "description": "get greeting message",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "greeting"
                ],
                "summary": "Greeting",
                "responses": {
                    "200": {
                        "description": "Hello, World!",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/novinopay/init": {
            "post": {
                "description": "Initialize a new payment transaction with NovinoPay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "novinopay"
                ],
                "summary": "Init Transaction",
                "parameters": [
                    {
                        "description": "Transaction Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novinopay.InitTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/novinopay.InitTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/novinopay.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/novinopay.Err"
                        }
                    }
                }
            }
        },
        "/novinopay/verify": {
            "post": {
                "description": "Verify a payment transaction with NovinoPay",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "novinopay"
                ],
                "summary": "Verify Transaction",
                "parameters": [
                    {
                        "description": "Verification Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/novinopay.VerifyTransactionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/novinopay.VerifyTransactionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/novinopay.Err"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/novinopay.Err"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "novinopay.Err": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "novinopay.InitTransactionData": {
            "type": "object",
            "properties": {
                "authority": {
                    "type": "string",
                    "example": "812F739E41057BAC22331918CD5B41C2"
                },
                "payment_url": {
                    "type": "string",
                    "example": "https://ipg.novinopay.com/StartPay/812F739E41057BAC22331918CD5B41C2"
                },
                "trans_id": {
                    "type": "integer",
                    "example": 337811
                },
                "wage": {
                    "type": "integer",
                    "example": 0
                },
                "wage_payer": {
                    "type": "string",
                    "example": "merchant"
                }
            }
        },
        "novinopay.InitTransactionRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 10000
                },
                "callback_method": {
                    "type": "string",
                    "example": "GET"
                },
                "callback_url": {
                    "type": "string",
                    "example": "http://localhost:9091/api/v1/novinopay/callback"
                },
                "card_pan": {
                    "type": "string",
                    "example": "6037861810449774"
                },
                "description": {
                    "type": "string",
                    "example": "NovinoPay Test"
                },
                "email": {
                    "type": "string",
                    "example": "a@b.com"
                },
                "invoice_id": {
                    "type": "string",
                    "example": "order_123456"
                },
                "merchant_id": {
                    "type": "string",
                    "example": "test"
                },
                "mobile": {
                    "type": "string",
                    "example": "09121234567"
                },
                "name": {
                    "type": "string",
                    "example": "ali yari"
                }
            }
        },
        "novinopay.InitTransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/novinopay.InitTransactionData"
                },
                "errors": {
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "عملیات موفقیت آمیز"
                },
                "status": {
                    "type": "string",
                    "example": "100"
                }
            }
        },
        "novinopay.VerifyTransactionData": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 1000
                },
                "authority": {
                    "type": "string",
                    "example": "812F739E41057BAC22331918CD5B41C2"
                },
                "buyer_ip": {
                    "type": "string",
                    "example": "5.113.185.222"
                },
                "card_pan": {
                    "type": "string",
                    "example": "504172******0613"
                },
                "invoice_id": {
                    "example": "null"
                },
                "payment_time": {
                    "type": "integer",
                    "example": 1663376322
                },
                "ref_id": {
                    "type": "string",
                    "example": "223003535268"
                },
                "trans_id": {
                    "type": "integer",
                    "example": 337811
                }
            }
        },
        "novinopay.VerifyTransactionRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer",
                    "example": 10000
                },
                "authority": {
                    "type": "string",
                    "example": "812F739E41057BAC22331918CD5B41C2"
                },
                "merchant_id": {
                    "type": "string",
                    "example": "test"
                }
            }
        },
        "novinopay.VerifyTransactionResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/novinopay.VerifyTransactionData"
                },
                "errors": {
                    "example": "null"
                },
                "message": {
                    "type": "string",
                    "example": "عمليات موفق"
                },
                "status": {
                    "type": "string",
                    "example": "100"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9091",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Payment Iran API",
	Description:      "Payment integration server for Iran gateways.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
